package com.mirigangneung.composition.service;
import com.mirigangneung.common.error.ApiException; import com.mirigangneung.composition.domain.*; import com.mirigangneung.composition.dto.*; import com.mirigangneung.composition.repository.*; import com.mirigangneung.infrastructure.ai.AiGenerationClient; import com.mirigangneung.infrastructure.storage.*; import org.springframework.http.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.multipart.MultipartFile; import java.io.*; import java.time.*; import java.util.*;
@Service public class CompositionService {private final CompositionJobRepository jobs;private final TemporaryImageStorage storage;private final Optional<AiGenerationClient> ai; public CompositionService(CompositionJobRepository j,TemporaryImageStorage s,Optional<AiGenerationClient>a){jobs=j;storage=s;ai=a;}
 @Transactional public CompositionStatusResponse create(MultipartFile photo,String onePick,String aspect){if(photo.isEmpty()||!List.of("image/jpeg","image/png","image/webp").contains(photo.getContentType()))throw new ApiException("UNSUPPORTED_IMAGE",HttpStatus.UNSUPPORTED_MEDIA_TYPE,"지원하지 않는 이미지 형식입니다.");try{String key=storage.save(photo.getInputStream(),photo.getContentType(),photo.getSize(),Instant.now().plusSeconds(86400));CompositionJob job=jobs.save(new CompositionJob(onePick,key,OffsetDateTime.now().plusDays(1)));if(ai.isPresent()){}return CompositionStatusResponse.from(job,false);}catch(IOException e){throw new ApiException("INTERNAL_ERROR",HttpStatus.INTERNAL_SERVER_ERROR,"이미지를 저장할 수 없습니다.");}}
 @Transactional(readOnly=true) public CompositionStatusResponse get(String id){CompositionJob j=find(id);return CompositionStatusResponse.from(j,j.getStatus()==CompositionStatus.DONE&&j.getResultStorageKey()!=null&&storage.exists(j.getResultStorageKey()));}
 @Transactional public CompositionStatusResponse retry(String id){CompositionJob j=find(id);if(j.getStatus()!=CompositionStatus.FAILED)throw new ApiException("INVALID_COMPOSITION_STATE",HttpStatus.CONFLICT,"재시도할 수 없는 상태입니다.");j.retry();return CompositionStatusResponse.from(j,false);}
 public CompositionJob find(String id){try{return jobs.findById(UUID.fromString(id)).orElseThrow(()->notFound());}catch(IllegalArgumentException e){throw notFound();}} private ApiException notFound(){return new ApiException("COMPOSITION_NOT_FOUND",HttpStatus.NOT_FOUND,"생성 작업을 찾을 수 없습니다.");}
 public InputStream download(String id){CompositionJob j=find(id);if(j.getExpiresAt().isBefore(OffsetDateTime.now()))throw new ApiException("COMPOSITION_EXPIRED",HttpStatus.GONE,"생성 결과가 만료되었습니다.");if(j.getResultStorageKey()==null||!storage.exists(j.getResultStorageKey()))throw new ApiException("COMPOSITION_NOT_FOUND",HttpStatus.NOT_FOUND,"생성 결과를 찾을 수 없습니다.");try{return storage.open(j.getResultStorageKey());}catch(IOException e){throw notFound();}}
}
